- block:
    - name: 'Develop tools'
      apt: name=build-essential
    
    - name: 'Install dnscrypt'
      script: install_dnscrypt-proxy.sh creates="{{ dnscrypt_proxy.exec }}"
  when: ansible_os_family == "Debian"

- block:
    - name: Ensure dnscrypt-proxy
      homebrew: name=dnscrypt-proxy
  when: ansible_os_family == "Darwin"

- block:
    - name: Ensure default resolvers file
      copy: src="dnscrypt-resolvers.csv" dest="{{ dnscrypt_proxy.resolvers_list }}" force=no
    - name: Update dnscrypt-proxy resolvers list if possible
      get_url:
        url: "https://github.com/jedisct1/dnscrypt-proxy/raw/master/dnscrypt-resolvers.csv"
        dest: "{{ dnscrypt_proxy.resolvers_list }}"
        force: yes
      ignore_errors: yes
